# Generated by Django 2.0.2 on 2018-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicroom', '0002_auto_20180306_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('0', '129'), ('1', '136'), ('2', '136'), ('3', '345')], max_length=3),
        ),
    ]
