# Generated by Django 2.0.2 on 2018-03-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicroom', '0003_auto_20180330_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('129', '0'), ('136', '1'), ('136', '2'), ('345', '3')], max_length=3),
        ),
    ]
